# Generated by Django 5.1.1 on 2024-09-29 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_guestbook_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestbook',
            name='link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
